name = "VEM"
uuid = "0facc6ad-73e5-4905-b0d9-bf31628cf88d"
authors = ["Carlos Fernando Baptista <cfd.baptista@gmail.com>"]
version = "0.1.0-DEV"

[deps]
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FillArrays = "1.13.0"
LinearAlgebra = "1.11.0"
StaticArrays = "1.9.15"
julia = "1.11.6"
