name = "VEM"
uuid = "6ac606dd-6b54-421d-8b39-236b88ac3fdc"
authors = ["Carlos Fernando Baptista <cfd.baptista@gmail.com>"]
version = "0.1.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.9"
